config/routes.rb
Rails.application.routes.draw do
  root to: 'charts#index'
  resources :charts do
    collection do
      get 'px1'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chart.rb
class Chart < ApplicationRecord
  
  # the cache key for the mixed values
  MIX = "mix"
  
  # ISIN code of some values
  CAC40   = 'FR0003500008'
  AI      = 'FR0000120073'
  RENAULT = 'FR0000131906'
  QUANTUM = 'FR0011648971'
  
  # CAC40
  # Load the date/value keypair into the cache
  # Each line indicates : 
  # l'identifiant de la valeur, la date, le cours d'ouverture, le plus haut, le plus bas, le cours de clôture et le volume de titres échangés. 
  def self.load_single_value(filepath)
    all_values = []
    isin = 0
    File.open(filepath).each_line do |line|
      values = line.split(';')
      all_values << [Date.strptime(values[1], '%d/%m/%Y'), values[2].to_f, values[3].to_f, values[4].to_f, values[5].to_f, values[6].to_i]
      isin = values[0]
    end
    Rails.cache.write(isin, all_values)
    
    return Rails.cache.fetch(isin)
  end
  
  # Combine the cac 40 graph with the other values
  def self.make_combined
    cac = Rails.cache.fetch(Chart::CAC40)
    
    hashes = []
    values = [Chart::CAC40, Chart::AI, Chart::RENAULT, Chart::QUANTUM]
    values.each do |isin|
      vals = Rails.cache.fetch(isin).last(230)
      first_val = vals[0][4] / 100
      h = {}
      vals.each do |val|
        date = val[0]
        # Normalize so it starts at 100
        val[4] /= first_val
        h[date] = {isin => val}
      end
      hashes << h
    end
    
    mix = hashes.shift
    while !hashes.empty? do
      mix = mix.merge!(hashes.shift){ |key,a,b| a.merge(b) }
    end
    Rails.cache.write(Chart::MIX, mix)
    
    return Rails.cache.fetch(Chart::MIX)
  end
  
  def self.make_px1_graph
    self.make_combined
    # TODO : reload the cache ?
    return unless Rails.cache.exist?(Chart::MIX)
    
    # The list of values we want
    isines = [Chart::CAC40, Chart::AI, Chart::RENAULT, Chart::QUANTUM]
    
    graph_data = []
    Rails.cache.fetch(Chart::MIX).each do |key,values|
      line = [key]
      isines.each do |isin|
        value = nil
        value = values[isin][4] if values[isin]
        line << value
      end
      graph_data << line
    end
    return graph_data
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]

  def px1
    respond_to do |format|
      format.json { render json: Chart.make_px1_graph, status: 200 }
    end
  end

  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to charts_url, notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params.fetch(:chart, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_for(chart) do |f| %>
  <% if chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/index.html.erb
<!--Div that will hold the pie chart-->
<div id="chart_div"></div>

app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form', chart: @chart %>

<%= link_to 'Back', charts_path %>

app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Charts</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charts.haml
!!! 5
%html
  %head
    %title Charts
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    -# Load the AJAX API
    = javascript_include_tag 'https://www.gstatic.com/charts/loader.js'

  %body
    = yield